# Generated by Django 3.1.7 on 2021-10-08 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0003_auto_20211008_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='inhabitants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='inhabitants'),
        ),
        migrations.AddField(
            model_name='building',
            name='type',
            field=models.IntegerField(choices=[(0, 'House'), (1, 'Apartment building')], default=0),
            preserve_default=False,
        ),
    ]
