# Generated by Django 3.1.7 on 2021-10-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20211008_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.IntegerField(choices=[(0, 'House'), (1, 'Apartment building')], default=0),
        ),
    ]
