# Generated by Django 3.1.7 on 2021-10-11 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0006_auto_20211011_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='admins',
            field=models.ManyToManyField(related_name='building_admins', to=settings.AUTH_USER_MODEL, verbose_name='admins'),
        ),
        migrations.AlterField(
            model_name='building',
            name='inhabitants',
            field=models.ManyToManyField(related_name='building_inhabitants', to=settings.AUTH_USER_MODEL, verbose_name='inhabitants'),
        ),
    ]
