# Generated by Django 3.1.7 on 2021-10-08 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0003_auto_20211008_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBulletinBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('text', models.TextField()),
                ('expiration_date', models.DateField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communities.community', verbose_name='community')),
            ],
            options={
                'verbose_name': 'Community bulletin board',
                'verbose_name_plural': 'Community bulletin boards',
            },
        ),
        migrations.CreateModel(
            name='BuildingBulletinBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('text', models.TextField()),
                ('expiration_date', models.DateField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communities.community', verbose_name='building')),
            ],
            options={
                'verbose_name': 'Building bulletin board',
                'verbose_name_plural': 'Building bulletin boards',
            },
        ),
    ]
