# Generated by Django 3.1.7 on 2021-10-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_auto_20211011_1734'),
        ('news', '0002_auto_20211011_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingnews',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildings.building', verbose_name='building'),
        ),
    ]
