# Generated by Django 3.1.7 on 2021-10-08 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20210310_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
