# Generated by Django 3.1.7 on 2021-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20211008_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=255, verbose_name='number'),
        ),
    ]
