# Generated by Django 3.1.7 on 2021-10-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_floors', '0003_auto_20211008_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingfloor',
            name='name',
        ),
        migrations.AddField(
            model_name='buildingfloor',
            name='number',
            field=models.IntegerField(default=1, verbose_name='number'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='buildingfloor',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique building floor'),
        ),
    ]
