# Generated by Django 3.1.7 on 2021-10-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_floors', '0004_auto_20211011_1839'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buildingfloor',
            name='unique building floor',
        ),
        migrations.AlterField(
            model_name='buildingfloor',
            name='number',
            field=models.CharField(max_length=5, verbose_name='number'),
        ),
    ]
